[package]
name = "karm_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
clap = { version = "4.0", features = ["derive"] }
termion = "3.0.0"
